/* =====================================================================
   22e_finalize.js — Control de calidad del banco: opciones de longitud
   semejante (sin pistas por longitud) y balanceo de claves A–D sin
   patrones. Las reescrituras conservan la concepción de cada distractor.
   ===================================================================== */
const OPTION_REWRITES = {
  'RA-01-C1-Q02': ['El SDI, índice de densidad de sedimentos.', 'La temperatura del agua de alimentación.', 'La salinidad (TDS) de la alimentación.', 'La profundidad de la toma de captación.'],
  'RA-01-C1-Q04': ['Aumentar el caudal desde la toma de 4 m para compensar la menor producción del filtro.', 'Pasar a la toma de 12 m con caudal moderado, ajustar la coagulación y vigilar SDI y ΔP.', 'Suspender la coagulación mientras dure la floración para ahorrar químicos y lodos.', 'Puentear temporalmente el filtro para que las membranas reciban más caudal.'],
  'RA-01-C1-Q05': ['Lavar los filtros siempre a la misma hora, con un calendario fijo para todo el año.', 'Elegir profundidad y caudal con umbrales de SDI, ΔP y clorofila, con margen y reserva.', 'Operar siempre al caudal máximo para acumular agua tratada antes de cada floración.', 'Confiar en un único sensor de turbidez en superficie para decidir cuándo cerrar.'],
  'RA-01-C2-Q01': ['Con el mismo caudal, aumentar el área efectiva de la rejilla reduce la velocidad.', 'La configuración C atrapa menos larvas que la A, según el índice de la tabla.', 'Si el caudal no cambia, el área de la rejilla no puede modificar la velocidad.', 'La configuración A supera el criterio de referencia de 0,15 m/s.'],
  'RA-01-C2-Q04': ['Elegir A porque maximiza el caudal y dejar las larvas a la autoridad pesquera.', 'Adoptar B, bajar el caudal en temporada de desove con la reserva y monitorear larvas.', 'Cerrar la toma de forma permanente para eliminar cualquier impacto sobre la fauna.', 'Usar C todo el año aunque no cubra la demanda y racionar el agua faltante.'],
  'RA-01-C2-Q05': ['Copiar exactamente el diseño y la ubicación relativa de la toma de Aridia.', 'Evaluar captación subsuperficial o profunda lejos del arrecife, lenta y monitoreada.', 'Ubicar la toma junto al arrecife, donde el agua es más clara y exige menos filtrado.', 'Elegir el sitio solo por el menor costo de tubería y ajustar el resto después.'],
  'RA-01-C3-Q04': ['Mantener los 100 m³/h y esperar a que la turbidez baje sola al pasar la tormenta.', 'Reducir caudal, lavar el filtro, ajustar coagulación y cubrir la demanda con la reserva.', 'Aumentar la presión de las membranas para compensar la turbidez y sostener producción.', 'Enviar el agua turbia a las membranas, que luego pueden limpiarse químicamente.'],
  'RA-01-C3-Q05': ['Fijar un único umbral de turbidez de entrada que cierre la toma de forma automática.', 'Responder por etapas según la tasa de cambio del ΔP y el pronóstico, con reservas y avisos.', 'Operar a caudal mínimo durante toda la temporada de lluvias, haya o no tormentas.', 'Duplicar el número de filtros y mantener la misma forma de operar la planta.'],
  'RA-02-C1-Q04': ['Solo aumentará la producción de permeado y ninguna otra variable relevante cambiará.', 'Disminuirá la salinidad del concentrado porque sale menos agua por el rechazo.', 'Puede subir la concentración, la incrustación y la energía: hay que revisar límites.', 'El caudal de alimentación dejará de influir en el desempeño del tren de membranas.'],
  'RA-02-C1-Q05': ['Maximizar la presión de alimentación para mantener la producción nominal de permeado.', 'Desactivar el pretratamiento para ahorrar energía y destinarla a las bombas de alta presión.', 'Mantener el H2 a plena carga y cubrir el agua con lo que quede en el tanque.', 'Reducir carga, proteger membranas, priorizar agua esencial y reprogramar flexibles.'],
  'RA-02-C2-Q04': ['Porque al subir la presión aumenta la salinidad del agua de mar que entra al tren.', 'Porque eleva el flujo, el depósito de ensuciantes y la energía, sin atacar la causa.', 'Porque la presión no influye en la energía y solo desgasta los sellos de la bomba.', 'Porque a mayor presión la recuperación cae y el tren termina produciendo menos.'],
  'RA-02-C2-Q05': ['Limpiar químicamente cada semana por precaución, aunque los indicadores no lo pidan.', 'Normalizar datos, fijar disparadores de limpieza e investigar el pretratamiento antes de forzar.', 'Subir la presión hasta el máximo del recipiente y limpiar solo cuando el tren falle.', 'Vigilar solo el caudal producido e ignorar la conductividad mientras haya permeado.'],
  'RA-02-C3-Q04': ['Subir la recuperación al máximo para producir más permeado con la misma energía.', 'Operar a menor carga dentro de límites, usar el tanque y desplazar cargas flexibles.', 'Apagar la OI durante las 6 h y esperar el sol sin tocar el agua del tanque.', 'Mantener 44 m³/h tomando la energía faltante de la reserva crítica de la batería.'],
  'RA-02-C3-Q05': ['Producir siempre al máximo y detener la planta solo cuando la energía se agote.', 'Llenar el tanque antes del evento, alinear la OI con el sol y fijar un mínimo de agua.', 'Desconectar la OI cada vez que una nube reduzca la generación, para cuidar la batería.', 'Elegir siempre la recuperación máxima para compensar cualquier caída de energía.'],
  'RA-03-C1-Q04': ['Descargar siempre en llenante, cuando la corriente es más fuerte y diluye más rápido.', 'Almacenar y descargar en repunte y vaciante con difusor, vigilando ambos receptores.', 'Acumular y descargar todo de golpe en vaciante para que la exposición dure menos.', 'Detener la planta durante toda la llenante y producir solo en las otras fases.'],
  'RA-03-C1-Q05': ['Usar las mismas ventanas de marea de Aridia, que ya demostraron proteger el manglar.', 'Medir en receptores, fijar umbrales por especie y adaptar ventanas a corrientes locales.', 'Descargar siempre lo más lejos posible de la costa, sin necesidad de monitorear.', 'Diluir la salmuera con agua de mar adicional antes de verterla, en todo momento.'],
  'RA-03-C2-Q04': ['Usar el estanque como destino final de toda la salmuera de la temporada seca.', 'Usarlo para mover descargas a ventanas favorables, con límite de llenado y control de fugas.', 'Retirar el revestimiento para que el suelo absorba parte de la salmuera y gane capacidad.', 'Llenarlo al máximo cada día para no descargar nada al mar durante la temporada.'],
  'RA-03-C2-Q05': ['Construir el estanque más grande posible y depender solo de él en la sequía.', 'Cuantificar volúmenes y combinar reducción, ventanas, almacenamiento y monitoreo.', 'Detener la desalinización toda la temporada seca para no generar salmuera.', 'Mezclar la salmuera con agua dulce para "neutralizarla" antes de almacenarla.'],
  'RA-03-C3-Q03': ['Costo energético 45 USD/t > precio 30 USD/t: no es rentable solo por energía.', 'Costo energético 4,5 USD/t < precio 30 USD/t: el proyecto es muy rentable.', 'Costo energético 300 USD/t, mucho mayor que el precio: no conviene evaluarlo.', 'El costo energético es cero, porque la sal ya está disuelta en la salmuera.'],
  'RA-03-C3-Q04': ['Aprobarla de inmediato porque convierte un residuo en un producto con mercado.', 'Evaluar energía, mercado, residuos, escala y riesgos; pilotear sin dejar la gestión de descarga.', 'Rechazar cualquier valorización por principio, porque toda extracción genera impactos.', 'Aprobarla si la venta del oxígeno de la electrólisis cubre la diferencia de costos.'],
  'RA-03-C3-Q05': ['El precio internacional de la sal, porque define si la venta cubre los costos.', 'Balances de masa y energía, mercado, madurez, impactos y aceptación social.', 'El tamaño de la planta de OI, porque a mayor escala la valorización conviene.', 'El número de minerales distintos que contiene la salmuera de la planta.'],
  'RA-04-C1-Q01': ['Con un pico de 450 kW, la energía del día nublado fue casi igual a la del despejado.', 'Las caídas bruscas de las 10 y las 13 h son coherentes con nubes pasajeras.', 'La energía diaria corresponde al área bajo la curva de potencia de cada día.', 'La potencia es nula durante la noche en ambos días, con o sin nubes.'],
  'RA-04-C1-Q04': ['Operar la OI a plena carga desde las 6 h, con batería hasta que salga el sol.', 'Concentrar la OI en ventanas de alta generación, reservar batería y desplazar el H2.', 'Programar todas las cargas suponiendo 450 kW disponibles durante todo el día.', 'Apagar la OI todo el día y esperar una jornada despejada para producir.'],
  'RA-04-C1-Q05': ['Planificar con el promedio anual de potencia pico, que resume bien el recurso solar.', 'Estimar energía horaria con banda de incertidumbre, reserva nocturna y cargas flexibles.', 'Instalar más paneles y mantener la misma operación que en la estación soleada.', 'Suponer que la eólica nocturna compensará exactamente el déficit solar.'],
  'RA-04-C2-Q01': ['Colocar turbinas más juntas siempre aumenta la producción total del parque.', 'La turbina aguas abajo recibe menos viento por el efecto estela de la primera.', 'Sobre 12 m/s la potencia de cada turbina queda limitada a la nominal.', 'Sobre 25 m/s la turbina se detiene por seguridad aunque haya mucho viento.'],
  'RA-04-C2-Q03': ['A 3D: 286 + 111 = 397 kW; a 7D: 286 + 186 = 472 kW.', 'A 3D: 286 + 286 = 572 kW; a 7D: también 572 kW.', 'A 3D: 286 + 286 = 572 kW; a 7D: 286 + 0 = 286 kW.', 'A 3D: 286 + 230 = 516 kW; a 7D: 286 + 114 = 400 kW.'],
  'RA-04-C2-Q04': ['Ubicarlas juntas a 3D en una sola fila para reducir el costo de cable y caminos.', 'Escalonarlas o separarlas ≥ 7D en la dirección dominante, aceptando más cableado.', 'Orientar cada turbina al azar para que las estelas se repartan de forma pareja.', 'Instalar solo una turbina en la franja para evitar por completo las estelas.'],
  'RA-04-C2-Q05': ['Copiar la separación entre turbinas de Aridia, que ya probó funcionar bien.', 'Usar la rosa de vientos local, modelar estelas en ambas direcciones y validar.', 'Estimar la producción con v³ a cualquier velocidad y elegir el sitio más ventoso.', 'Ubicar las turbinas donde el viento sea máximo, sin considerar el cut-out.'],
  'RA-04-C3-Q04': ['Programar el electrolizador a 300 kW y cubrir con la batería cualquier faltante.', 'Asegurar esenciales y OI con el escenario pesimista y el H2 solo con excedente real.', 'Apagar la OI durante la tarde para garantizar la producción de H2 comprometida.', 'Programar todas las cargas con el escenario optimista y corregir si algo falla.'],
  'RA-04-C3-Q05': ['Una regla fija basada solo en la hora del día, igual en todas las estaciones.', 'Pronósticos probabilísticos (p10 para lo crítico), prioridades declaradas y revisión.', 'Maximizar siempre el H2, porque almacena el excedente para cualquier temporada.', 'Eliminar la batería para simplificar el despacho y reducir costos.'],
  'RA-05-C1-Q01': ['Como la batería tiene 250 kW, puede suministrar 250 kW durante toda la noche.', 'La batería almacena energía producida por otras fuentes; no la genera.', 'La potencia máxima limita qué tan rápido puede entregar su energía.', 'La reserva mínima protege servicios esenciales ante eventos inciertos.'],
  'RA-05-C1-Q04': ['Usar toda la batería en las primeras horas para maximizar el H2 mientras se pueda.', 'Reservarla para lo crítico, posponer flexibles y usar la reserva solo si falta viento.', 'Ignorar el pronóstico de viento débil y operar todas las cargas de forma normal.', 'Desconectar la carga crítica durante la noche para proteger la batería.'],
  'RA-05-C1-Q05': ['Descargar siempre hasta el mínimo físico cada noche para usar toda la capacidad.', 'Fijar una reserva dinámica según el p10, cargar con excedente y modular flexibles.', 'Mantener la batería siempre al 100 % y usarla solo en emergencias declaradas.', 'Decidir la descarga de cada noche con el pronóstico promedio de viento y sol.'],
  'RA-05-C2-Q01': ['Si el SOC sigue en 60 %, la energía disponible es la misma que antes de la falla.', 'La potencia máxima disponible disminuyó al perder uno de los cuatro módulos.', 'La capacidad útil de la batería disminuyó de 1 000 a 750 kWh.', 'Las cargas conectadas deben revisarse ante la nueva potencia máxima.'],
  'RA-05-C2-Q04': ['Nada cambia: mientras el SOC sea alto, la batería cubre las mismas cargas.', 'Con 187,5 kW no alcanza para ambas: priorizar esenciales y mover la OI al día.', 'Conviene apagar los servicios esenciales de noche para seguir operando la OI.', 'Basta con cargar la batería al 100 % para recuperar la potencia perdida.'],
  'RA-05-C2-Q05': ['Reemplazar los módulos por uno único y grande para simplificar el control.', 'Redundancia N+1, operación modular, mantenimiento predictivo y prioridades.', 'Operar siempre a potencia máxima para aprovechar cada módulo mientras funcione.', 'Eliminar la reserva mínima para disponer de más energía útil tras una falla.'],
  'RA-05-C3-Q02': ['Electrolizador', 'Riego programado', 'Servicios críticos', 'Ósmosis inversa'],
  'RA-05-C3-Q04': ['Electrolizador → OI → servicios críticos → bombeo potable → riego.', 'BESS estable → críticos → bombeo → OI (con sol) → riego → H2 con excedente.', 'Conectar todas las cargas a la vez y luego desconectar las que fallen.', 'OI → riego → servicios críticos → bombeo potable → electrolizador.'],
  'RA-05-C3-Q05': ['Usar el mismo protocolo del mediodía, porque las prioridades no cambian de noche.', 'Reconectar solo lo que sostienen batería y eólica, por etapas y con umbrales de SOC.', 'Esperar al amanecer sin reconectar ninguna carga para proteger la batería.', 'Reconectar primero el electrolizador para producir H2 de respaldo nocturno.'],
  'RA-06-C1-Q03': ['Mínimo ≈ 274 kg de agua; con purificación ≈ 422 kg de entrada.', 'Mínimo ≈ 30,7 kg de agua; con purificación ≈ 47 kg de entrada.', 'Mínimo ≈ 274 kg de agua; con purificación ≈ 178 kg de entrada.', 'No se requiere agua de entrada, porque el H2 producido es un gas.'],
  'RA-06-C1-Q04': ['Operarlo a plena carga todo el día y completar con batería cuando falte excedente.', 'Operarlo solo con excedente, sobre su carga mínima, sin competir por agua y con trazabilidad.', 'Priorizar el H2 sobre el tanque de agua potable, porque su valor económico es mayor.', 'Mantenerlo apagado siempre para no gastar agua en una región árida.'],
  'RA-06-C1-Q05': ['Replicar el mismo electrolizador y su programación, que ya funcionan en Aridia.', 'Dimensionar según horas de excedente y agua, costos nivelados y prioridades locales.', 'Maximizar la producción de H2 porque es una energía limpia en cualquier contexto.', 'Usar electricidad de cualquier origen para mantener la producción constante.'],
  'RA-06-C2-Q04': ['Es poco en términos absolutos, así que no requiere discusión con la comunidad.', 'Evaluarlo frente al agua local, transparentarlo y priorizar el agua esencial.', 'Debe prohibirse cualquier producción de H2 mientras exista escasez de agua.', 'Se resuelve vendiendo el oxígeno subproducto para pagar agua de otra región.'],
  'RA-06-C2-Q05': ['Extraer agua del acuífero local según se necesite, porque está disponible.', 'Agua desalinizada con salmuera gestionada, enfriamiento seco y retiro medido.', 'Usar agua potable de la red, porque ya está tratada y reduce costos.', 'Concentrarse en la electricidad renovable, que es la restricción principal.'],
  'RA-06-C3-Q02': ['DETENER → VENTILAR → DETECTAR → AISLAR → VERIFICAR → AUTORIZAR REINICIO', 'DETECTAR → AISLAR → DETENER → VENTILAR → VERIFICAR → AUTORIZAR REINICIO', 'DETECTAR → VENTILAR → AUTORIZAR REINICIO → AISLAR → DETENER → VERIFICAR', 'AISLAR → DETECTAR → VERIFICAR → AUTORIZAR REINICIO → VENTILAR → DETENER'],
  'RA-06-C3-Q03': ['Aislar el suministro, detener el equipo, ventilar, alejar al personal y verificar.', 'Seguir produciendo, abrir puertas y ventanas y esperar a que el aire se renueve.', 'Silenciar el detector hasta confirmar que no es una falsa alarma del sensor.', 'Reiniciar el electrolizador para que el flujo de gas "purgue" la sala.'],
  'RA-06-C3-Q04': ['Porque el hidrógeno nunca termina de dispersarse de una sala cerrada.', 'Porque falta hallar la causa, confirmar lecturas estables y obtener autorización.', 'Porque la ventilación consume mucha energía y conviene apagarla primero.', 'Porque el reglamento solo permite reiniciar equipos durante la noche.'],
  'RA-06-C3-Q05': ['Confiar en la experiencia del operador más antiguo para decidir cada caso.', 'Sensores redundantes, interlocks no anulables, simulacros y comunicación clara.', 'Reducir el número de sensores para evitar alarmas que interrumpen el trabajo.', 'Trabajar más rápido dentro de la sala para salir antes de que ocurra una fuga.'],
  'RA-07-C1-Q01': ['Como el permeado es casi agua pura, es ideal para cualquier cultivo sin ajustes.', 'El boro del permeado podría superar la tolerancia orientativa del fríjol.', 'El agua del pozo aporta mucha más salinidad que el permeado de OI.', 'Mezclar fuentes cambia al mismo tiempo la EC y el boro del agua de riego.'],
  'RA-07-C1-Q03': ['EC ≈ 0,82 dS/m y boro ≈ 0,86 mg/L: el boro aún supera el umbral.', 'EC ≈ 0,82 dS/m y boro ≈ 0,40 mg/L: cumple ambos límites.', 'EC ≈ 2,6 dS/m y boro ≈ 1,1 mg/L: no cumple ningún límite.', 'EC ≈ 2,65 dS/m y boro ≈ 1,4 mg/L, porque los valores se suman.'],
  'RA-07-C1-Q04': ['Regar el fríjol solo con permeado y aumentar el volumen para diluir el boro.', 'Mezclar y remineralizar, dar al fríjol el agua con menos boro y llevar tolerantes al resto.', 'Regar todas las parcelas solo con agua del pozo, que tiene menos boro que el permeado.', 'Cambiar todas las parcelas a un único cultivo de alto rendimiento tolerante al boro.'],
  'RA-07-C1-Q05': ['Aplicar los umbrales de esta finca como reglas universales para cualquier cultivo.', 'Analizar fuentes, suelo y drenaje; mezclar por cultivo y etapa; monitorear con la gente.', 'Elegir siempre la fuente de agua más barata y ajustar el cultivo a esa agua.', 'Regar con más volumen para lavar las sales y el boro, sea cual sea el suelo.'],
  'RA-07-C2-Q01': ['Surcos y goteo necesitan el mismo volumen bruto, porque el cultivo es el mismo.', 'La necesidad neta de agua depende del cultivo, su etapa y el clima.', 'La eficiencia del sistema de riego cambia el volumen bruto a aplicar.', 'La cobertura del suelo puede reducir la evaporación desde la superficie.'],
  'RA-07-C2-Q04': ['Riego por surcos al mediodía, cuando el suelo está más seco y absorbe mejor.', 'Goteo con cobertura, riego temprano, sensores de humedad y ajuste por etapa.', 'Goteo sin cobertura con un calendario fijo igual para toda la temporada.', 'Aspersión en las horas de más calor para enfriar las hojas del cultivo.'],
  'RA-07-C2-Q05': ['Mantener el mismo calendario de riego y esperar a que vuelva la lluvia.', 'Priorizar etapas críticas, cobertura, especies tolerantes y reparto acordado del agua.', 'Duplicar el riego antes de la sequía para "guardar" agua en el suelo.', 'Sembrar solo el cultivo más rentable para compensar las pérdidas del año.'],
  'RA-07-C3-Q01': ['Responder al estrés salino aumentando el volumen siempre corrige el problema.', 'La demanda total de 15 m³/d supera la disponibilidad de 12 m³/d.', 'Las tres parcelas toleran de forma distinta la salinidad del agua.', 'La etapa de cada cultivo cambia la prioridad del riego en la sequía.'],
  'RA-07-C3-Q03': ['P1: 6, P2: 5 y P3: 1, atendiendo las parcelas en el orden de la tabla.', 'P1: 6 (floración, mejor agua), P2: 3 (tolerante, pozo), P3: 3 (cobertura).', 'P1: 0, P2: 6 y P3: 6, porque sorgo y nopal producen más con agua.', 'P1: 4, P2: 4 y P3: 4, repartiendo por igual entre las tres parcelas.'],
  'RA-07-C3-Q04': ['Pasar a monocultivo del cultivo más productivo para simplificar el manejo.', 'Asociaciones diversas, cobertura, polinizadores, semillas locales y monitoreo.', 'Fertilización química intensiva para compensar el estrés de la sequía.', 'Arar profundamente cada semana para romper la costra y airear el suelo.'],
  'RA-07-C3-Q05': ['Esperar a que la planta de OI aumente su producción para cubrir el déficit.', 'Plan participativo: prioridades, semillas adaptadas, calidad, cobertura y lluvia.', 'Contratar agua en camiones durante la sequía y mantener las mismas prácticas.', 'Reducir el área cultivada a cero hasta que termine la sequía.'],
  'RA-08-C1-Q01': ['Mantener el electrolizador a máxima carga aunque haya déficit y turbidez.', 'Evaluar la calidad del agua de alimentación antes de sostener la OI.', 'Mantener los servicios esenciales durante todo el evento.', 'Considerar la batería y el almacenamiento de agua como amortiguadores.'],
  'RA-08-C1-Q04': ['Forzar la OI y el H2 a plena carga para aprovechar la eólica alta.', 'Priorizar servicios, revisar pretratamiento, modular la OI y pausar el H2.', 'Descargar completamente la batería y mantener todas las cargas sin cambios.', 'Cerrar toda la planta de inmediato, sin evaluar ninguna variable.'],
  'RA-08-C1-Q05': ['Usar una regla fija basada solo en la generación FV de cada hora.', 'Maximizar siempre el H2 para almacenar energía para futuras tormentas.', 'Pronóstico, reservas mínimas, calidad de agua, prioridades y revisión comunitaria.', 'Eliminar sensores redundantes para simplificar las decisiones en crisis.'],
  'RA-08-C2-Q01': ['La cuota fija puede cumplirse en cualquier clima sin afectar otros servicios.', 'La producción de H2 depende del excedente renovable disponible cada día.', 'Usar respaldo de la red fósil afecta el atributo "verde" del H2.', 'Una cuota fija choca con la variabilidad de la generación renovable.'],
  'RA-08-C2-Q03': ['Produce ≈ 82 kg/día; faltan ≈ 38 kg (≈ 2 100 kWh de otra fuente).', 'Produce 120 kg/día; no hay déficit porque el excedente alcanza.', 'Produce ≈ 247 kg/día; sobra hidrógeno para vender en el mercado.', 'Produce ≈ 38 kg/día; faltan ≈ 82 kg que exigen otra fuente.'],
  'RA-08-C2-Q04': ['Firmarlo tal como está, porque el H2 es el futuro energético de la región.', 'Renegociar cuotas ligadas al excedente, con prioridad del agua y origen verificado.', 'Cumplir la cuota usando la reserva de la batería cuando falte excedente.', 'Rechazar toda producción de H2 en Aridia por sus riesgos y costos.'],
  'RA-08-C2-Q05': ['Que el financiador decida con su equipo técnico, sin consulta externa.', 'Criterios públicos, participación, cuotas adaptativas y auditoría eléctrica.', 'Un índice único de rentabilidad para comparar contratos rápidamente.', 'Aceptar cualquier contrato que traiga inversión y empleo a la región.'],
  'RA-08-C3-Q01': ['La alternativa de menor costo inicial es necesariamente la mejor.', 'Las alternativas compiten en varios criterios a la vez, no en uno.', 'Los pesos asignados a los criterios son decisiones discutibles.', 'La participación de la comunidad es un criterio relevante.'],
  'RA-08-C3-Q04': ['Elegir A porque tiene la mayor confiabilidad, sin necesidad de más discusión.', 'Declarar pesos con la comunidad, analizar incertidumbre, explorar híbridos y quién paga.', 'Sumar los valores normalizados y elegir el mayor, sin declarar pesos.', 'Elegir B porque es la preferida por el equipo técnico del proyecto.'],
  'RA-08-C3-Q05': ['Un índice único calculado por el gemelo digital para cada expansión.', 'Criterios y pesos públicos, escenarios con incertidumbre, piloto y revisión.', 'Elegir siempre la ampliación de tubería, que es la opción más confiable.', 'Decidir por votación comunitaria sin presentar información técnica.'],
  'RA-09-C1-Q03': ['La diferencia supera la incertidumbre combinada: hay variabilidad o mala ubicación.', 'Son iguales dentro de la incertidumbre de ± 3 % de cada sensor.', 'El sensor que marca 26 % está roto y debe descartarse.', 'Se deben promediar (22 %) y descartar la diferencia entre ambos.'],
  'RA-09-C1-Q04': ['Venderlo tal cual, porque las lecturas ya muestran tendencias útiles.', 'Recalibrar con suelo salino, replicar, comparar con medidas manuales y protegerlo.', 'Cambiar la carcasa por una más vistosa para que más agricultores lo usen.', 'Aumentar la frecuencia de lectura para que el promedio corrija el sesgo.'],
  'RA-09-C1-Q05': ['Instalar un sensor por finca y automatizar el riego con sus lecturas.', 'Sensores replicados, calibración local, mantenimiento y registros compartidos.', 'Confiar en el pronóstico del clima en lugar de medir la humedad del suelo.', 'Usar la calibración de Aridia sin cambios, porque el sensor es el mismo.'],
  'RA-09-C2-Q01': ['Comunicar solo el escenario más probable evita confusión y es suficiente.', 'Existe un 30 % de probabilidad de algún tipo de racionamiento.', 'Las acciones recomendadas dependen del escenario que ocurra.', 'La incertidumbre del pronóstico debe explicarse con claridad.'],
  'RA-09-C2-Q03': ['Un solo indicador grande que diga "Agua: OK" mientras sea probable.', 'Barras por escenario con probabilidad, acción sugerida y fecha de actualización.', 'Un mapa de colores de la ciudad, sin leyenda, para no saturar.', 'Una tabla técnica con los caudales horarios previstos de la semana.'],
  'RA-09-C2-Q04': ['"Todo está bien: no habrá problemas de agua, no se preocupen."', '"Lo más probable es que alcance (7 de 10); hay 3 de 10 de turnos. Actualizamos el miércoles."', '"Todavía no sabemos nada sobre el agua de la próxima semana."', '"Habrá racionamiento severo; reduzcan el consumo desde hoy."'],
  'RA-09-C2-Q05': ['Un comunicado técnico mensual con los datos completos del gemelo digital.', 'Canales locales, lenguaje claro, escenarios con acciones, actualizaciones y diálogo.', 'Comunicar únicamente cuando ya hay una crisis para no generar alarma.', 'Delegar los mensajes al gemelo digital, que publica sus pronósticos.'],
  'RA-09-C3-Q01': ['Un índice único alto garantiza que todos los actores están bien servidos.', 'Con su peso actual, la equidad hídrica no influye en el índice.', 'Sumar unidades distintas sin normalizar no tiene sentido físico.', 'Los pesos ocultos impiden discutir quién gana y quién pierde.'],
  'RA-09-C3-Q02': ['Costo de operación', 'Agua entregada', 'H2 exportado', 'Equidad hídrica'],
  'RA-09-C3-Q03': ['Que muestra el resultado con decimales, lo que sugiere falsa precisión.', 'Que suma unidades incompatibles sin normalizar y con pesos no declarados.', 'Que incluye cuatro criterios, cuando bastaría con uno o dos.', 'Que se actualiza solo una vez al día y no en tiempo real.'],
  'RA-09-C3-Q04': ['Subir el peso del H2 para que el índice refleje mejor el desempeño.', 'Criterios separados y normalizados, pesos declarados, incertidumbre y afectados.', 'Eliminar la equidad del tablero para simplificar la lectura.', 'Mostrar solo el índice, con más decimales para mayor precisión.'],
  'RA-09-C3-Q05': ['Una revisión técnica anual cerrada del equipo que diseñó el tablero.', 'Talleres periódicos con actores, registro de cambios y pruebas de comprensión.', 'Delegar los pesos al algoritmo de optimización del gemelo digital.', 'Mantener el tablero sin cambios para que la gente no se confunda.'],
};
const DIST_REWRITES = {
  'RA-06-C3-Q02': [null, null, 'Ventila y autoriza el reinicio antes de aislar y detener.', 'Autoriza el reinicio antes de ventilar y detener el equipo.'],
  'RA-09-C3-Q03': ['Los decimales no son el problema central.', null, 'El número de criterios no es el problema.', 'La frecuencia de actualización no corrige la agregación.'],
  'RA-06-C3-Q03': [null, 'No aísla ni detiene: la fuente sigue activa.', 'Silenciar o desactivar sensores está prohibido.', 'Reiniciar agrava el riesgo.'],
};
/* Ajustes finos de longitud: ningún patrón "la clave es la más larga" */
const LENGTH_PATCH = {
  'RA-01-C1-Q02': { 3: 'La profundidad a la que se ubica la toma de captación.' },
  'RA-01-C1-Q04': { 0: 'Aumentar el caudal desde la toma de 4 m para compensar la menor producción del filtro saturado.' },
  'RA-04-C2-Q04': { 0: 'Ubicarlas juntas a 3D en una sola fila para reducir el costo de cable, caminos y obra.' },
  'RA-05-C2-Q04': { 2: 'Conviene apagar los servicios esenciales durante la noche para seguir operando la OI.' },
  'RA-06-C3-Q05': { 3: 'Trabajar más rápido dentro de la sala para salir antes de que pueda ocurrir una fuga.' },
  'RA-08-C2-Q03': { 2: 'Produce ≈ 247 kg/día; sobra hidrógeno para vender en el mercado regional.' },
  'RA-01-C3-Q04': { 2: 'Aumentar la presión de las membranas para compensar la turbidez y sostener la producción.' },
  'RA-02-C2-Q04': { 0: 'Porque al subir la presión aumenta la salinidad del agua de mar que entra al tren de OI.' },
  'RA-04-C3-Q01': { 1: 'El excedente disponible para el electrolizador depende del escenario que ocurra.' },
  'RA-05-C1-Q02': { 0: '23,75 kWh', 2: '250,0 kWh', 3: '522,5 kWh' },
  'RA-05-C1-Q05': { 3: 'Decidir la descarga de cada noche con el pronóstico promedio de viento y de sol.' },
  'RA-05-C3-Q02': { 0: 'Electrolizador flexible' },
  'RA-06-C2-Q05': { 0: 'Extraer agua del acuífero local según se necesite, porque hoy está disponible.' },
  'RA-06-C3-Q03': { 1: 'Seguir produciendo, abrir puertas y ventanas y esperar a que el aire se renueve solo.' },
  'RA-07-C1-Q03': { 3: 'EC ≈ 2,65 dS/m y boro ≈ 1,4 mg/L, porque los valores de ambas fuentes se suman.' },
  'RA-09-C3-Q03': { 0: 'Que muestra el resultado con decimales, lo que sugiere una precisión que no tiene.' },
  'RA-01-C1-Q05': { 2: 'Operar siempre al caudal máximo para acumular agua tratada antes de cada nueva floración.' },
  'RA-01-C2-Q04': { 2: 'Cerrar la toma de forma permanente para eliminar cualquier impacto sobre la fauna marina.' },
  'RA-02-C3-Q04': { 3: 'Mantener los 44 m³/h tomando la energía que falte de la reserva crítica de la batería.' },
  'RA-03-C2-Q04': { 2: 'Retirar el revestimiento para que el suelo absorba parte de la salmuera y así gane capacidad.' },
  'RA-05-C3-Q05': { 0: 'Usar el mismo protocolo del mediodía, porque las prioridades no cambian durante la noche.' },
  'RA-06-C1-Q05': { 2: 'Maximizar la producción de H2 porque es una energía limpia en cualquier contexto posible.' },
  'RA-08-C1-Q01': { 3: 'Considerar la batería y el almacenamiento de agua como amortiguadores del evento.' },
  'RA-03-C1-Q05': { 0: 'Usar las mismas ventanas de marea de Aridia, que ya demostraron proteger bien el manglar.' },
  'RA-03-C2-Q05': { 3: 'Mezclar la salmuera con agua dulce para "neutralizarla" antes de almacenarla o verterla.' },
  'RA-04-C1-Q05': { 0: 'Planificar con el promedio anual de potencia pico, que resume bien el recurso solar del sitio.' },
  'RA-04-C3-Q04': { 2: 'Apagar la OI durante toda la tarde para garantizar la producción de H2 comprometida.' },
  'RA-05-C1-Q04': { 0: 'Usar toda la batería en las primeras horas de la noche para maximizar la producción de H2.' },
  'RA-07-C3-Q03': { 3: 'P1: 4, P2: 4 y P3: 4, repartiendo el agua por igual entre las tres parcelas.' },
  'RA-07-C3-Q04': { 0: 'Pasar a monocultivo del cultivo más productivo para simplificar el manejo del agua.' },
  'RA-07-C3-Q05': { 0: 'Esperar a que la planta de OI aumente su producción para cubrir todo el déficit agrícola.' },
  'RA-08-C3-Q05': { 2: 'Elegir siempre la ampliación de tubería, que es la opción más confiable y conocida.' },
  'RA-09-C1-Q05': { 2: 'Confiar en el pronóstico del clima en lugar de medir directamente la humedad del suelo.' },
  'RA-05-C2-Q01': { 1: 'La potencia máxima disponible disminuyó al perder uno de los cuatro módulos iguales.' },
  'RA-05-C3-Q04': { 2: 'Conectar todas las cargas a la vez y luego desconectar una por una las que fallen.' },
  'RA-06-C2-Q01': { 1: 'El retiro real de agua supera el mínimo estequiométrico de la reacción.', 2: 'El enfriamiento puede ser un consumo de agua importante.' },
  'RA-07-C1-Q04': { 2: 'Regar todas las parcelas solo con agua del pozo, que tiene menos boro que el permeado de OI.' },
  'RA-08-C2-Q01': { 1: 'La producción diaria de H2 depende del excedente renovable disponible cada día.' },
  'RA-04-C3-Q05': { 2: 'Maximizar siempre el H2, porque almacena el excedente renovable para cualquier temporada.' },
  'RA-07-C1-Q05': { 3: 'Regar siempre con más volumen para lavar las sales y el boro, sea cual sea el tipo de suelo.' },
  'RA-08-C2-Q05': { 3: 'Aceptar cualquier contrato que traiga inversión, empleo y nuevas obras a toda la región.' },
  'RA-09-C1-Q03': { 3: 'Se deben promediar ambas lecturas (22 %) y descartar la diferencia entre los sensores.' },
  'RA-09-C2-Q04': { 0: '"Todo está bien: no habrá ningún problema de agua la próxima semana, no se preocupen."', 3: '"Habrá racionamiento severo en toda la ciudad; reduzcan el consumo de agua desde hoy mismo."' },
};
DIST_REWRITES['RA-05-C1-Q02'] = ['Error de escala (orden de magnitud).', null, 'Ignora la eficiencia de descarga (0,25 × 1 000).', 'Ignora la reserva mínima (0,55 × 1 000 × 0,95).'];
(function finalizeBank() {
  for (const q of QBANK) {
    const o = OPTION_REWRITES[q.id];
    if (o) q.options = o.slice();
    const lp = LENGTH_PATCH[q.id];
    if (lp) for (const k in lp) q.options[k] = lp[k];
    const d = DIST_REWRITES[q.id];
    if (d) q.dist = q.dist.map((x, i) => d[i] || x);
    q.distractorRationales = q.dist;
  }
  // balanceo: elige la posición de la clave con menor frecuencia acumulada (desempate aleatorio)
  const r = RNG(424242);
  const counts = [0, 0, 0, 0];
  const rot = (len, k, d) => { const ord = Array.from({ length: len }, (_, i) => i); const it = ord.splice(k, 1)[0]; ord.splice(d, 0, it); return ord; };
  for (const q of QBANK) {
    let cands;
    if (q.ordered) cands = [{ key: q.key, order: [0, 1, 2, 3] }, { key: 3 - q.key, order: [3, 2, 1, 0] }];
    else cands = [0, 1, 2, 3].map(d => ({ key: d, order: rot(4, q.key, d) }));
    const minC = Math.min(...cands.map(c => counts[c.key]));
    const pool = cands.filter(c => counts[c.key] <= minC + (q.ordered ? 0 : 1));
    const pickC = pool[Math.floor(r() * pool.length)];
    q.options = pickC.order.map(i => q.options[i]); q.dist = pickC.order.map(i => q.dist[i]); q.distractorRationales = q.dist; q.key = pickC.key;
    counts[q.key]++;
    if (q.retry) { const t2 = Math.floor(r() * 4); const o2 = q.retry.ordered ? [0, 1, 2, 3] : rot(4, q.retry.key, t2); q.retry = Object.assign({}, q.retry, { options: o2.map(i => q.retry.options[i]), dist: o2.map(i => q.retry.dist[i]), key: o2.indexOf(q.retry.key) }); q.retryVariant = q.retry; }
  }
})();
