/* =====================================================================
   23_codex.js — ATLAS DEL NEXO: fichas científicas, personajes,
   adversarios y fuentes. Desbloqueo progresivo.
   Las cifras de escenario son supuestos de simulación salvo que se
   indique fuente y año.
   ===================================================================== */

const CODEX_SECTIONS = [
  ['agua', 'Agua', 'water'], ['desal', 'Desalinización', 'membrane'], ['salmuera', 'Salmuera', 'drop_brine'], ['solar', 'Solar', 'sun'],
  ['eolica', 'Eólica', 'wind'], ['almac', 'Almacenamiento', 'battery'], ['h2', 'Hidrógeno', 'h2'], ['agro', 'Agroecología', 'leaf'],
  ['steam', 'STEAM', 'flask'], ['econ', 'Economía y decisión', 'coin'], ['pers', 'Personajes', 'person'], ['adv', 'Adversarios', 'warn'], ['fuentes', 'Fuentes', 'book'],
];
const SIM_NOTE = 'Supuesto de simulación para fines educativos.';
const SRC = {
  fao56: 'Allen, R. G., Pereira, L. S., Raes, D. y Smith, M. (1998). Crop evapotranspiration. FAO Irrigation and Drainage Paper 56. FAO, Roma. (Consultar también la edición revisada de FAO, 2025.)',
  fao29: 'Ayers, R. S. y Westcot, D. W. (1985). Water quality for agriculture. FAO Irrigation and Drainage Paper 29 Rev. 1. FAO, Roma.',
  faoDesal: 'FAO (2025). Desalination and agriculture: Balancing opportunities and challenges in the context of changing climate. FAO, Roma.',
  fao10: 'FAO (2018). The 10 Elements of Agroecology: Guiding the transition to sustainable food and agricultural systems. FAO, Roma.',
  irenaWater: 'IRENA y Bluerisk (2023). Water for hydrogen production. International Renewable Energy Agency, Abu Dabi.',
  irenaStrat: 'IRENA (2024). Green hydrogen strategy: A guide to design. International Renewable Energy Agency, Abu Dabi.',
  doeElec: 'U.S. Department of Energy, Hydrogen and Fuel Cell Technologies Office. Hydrogen Production: Electrolysis (consulta en línea).',
  doeShot: 'U.S. DOE (2024). Hydrogen Shot: Water Electrolysis Technology Assessment.',
  pnnl: 'U.S. DOE FEMP / PNNL (2013). Reverse Osmosis Optimization.',
  iea: 'IEA (2026). Global Hydrogen Review 2026. International Energy Agency, París.',
  unesco: 'UNESCO IBE. Designing a contemporary STEM curriculum.',
  ideam: 'IDEAM. Análisis de los potenciales de la radiación global en La Guajira (Atlas de radiación solar de Colombia).',
  upme: 'UPME. Información energética y recursos renovables de La Guajira.',
  minenergia: 'Ministerio de Minas y Energía de Colombia (2021). Hoja de Ruta del Hidrógeno en Colombia.',
  elimelech: 'Elimelech, M. y Phillip, W. A. (2011). The future of seawater desalination: energy, technology, and the environment. Science, 333(6043), 712–717.',
  voutchkov: 'Voutchkov, N. (2018). Energy use for membrane seawater desalination – current status and trends. Desalination, 431, 2–14.',
  stoich: 'Estequiometría: 2 H2O → 2 H2 + O2; masas molares H2O = 18,015 g/mol, H2 = 2,016 g/mol.',
};

const CODEX = [
  /* ---------------- AGUA ---------------- */
  { id: 'agua_mar', sec: 'agua', title: 'Agua de mar: composición variable', def: 'Solución de sales (sobre todo cloruro de sodio, magnesio, sulfatos, calcio y bicarbonatos) cuya concentración y temperatura cambian con la estación, las corrientes, la lluvia, la evaporación y la cercanía a desembocaduras.', vars: 'Sólidos disueltos totales (TDS), temperatura (T), conductividad (EC).', units: 'TDS en g/L o mg/L; T en °C; EC en mS/cm o dS/m.', rel: 'Más TDS → mayor presión osmótica → más presión necesaria en ósmosis inversa. Más temperatura → mayor permeabilidad de membrana, pero también más paso de sal.', ex: 'En Aridia la alimentación varía entre 34 y 38 g/L según la estación (' + SIM_NOTE + ')', limits: 'El juego usa TDS como variable agregada; no modela especiación iónica ni equilibrio de carbonatos.', error: 'Suponer que el agua de mar tiene composición constante.', src: 'Salinidad oceánica media ≈ 35 g/kg (oceanografía general). ' + SRC.faoDesal, use: 'Nivel 01: el dron de muestreo revela que dos puntos de la costa tienen salinidad y turbidez distintas.' },
  { id: 'turbidez', sec: 'agua', title: 'Turbidez y sólidos suspendidos', def: 'Medida de cuánto dispersan la luz las partículas en el agua (arena fina, limo, materia orgánica, floraciones de algas). No es lo mismo que salinidad: un agua puede ser muy salada y cristalina.', vars: 'Turbidez (NTU), sólidos suspendidos totales (SST), índice de ensuciamiento (SDI).', units: 'NTU; mg/L; SDI adimensional (minutos de ensayo normalizados).', rel: 'Más turbidez → más carga de sólidos para el pretratamiento → mayor diferencial de presión en filtros y riesgo de ensuciar membranas.', ex: 'Tras una tormenta, la turbidez sube de 2 a 40 NTU en pocas horas (' + SIM_NOTE + ')', limits: 'La turbidez simulada se transporta como un pulso que avanza; no se modela granulometría.', error: 'Confundir "agua clara" con "agua apta" o con "agua desalinizada".', src: SRC.pnnl, use: 'Nivel 01: el pulso de turbidez avanza desde mar adentro y LIMEN cierra la toma antes de que llegue.' },
  { id: 'captacion', sec: 'agua', title: 'Captación de agua de mar', def: 'Estructura que extrae agua de mar: tomas abiertas (tubería con rejillas mar adentro) o captación subsuperficial (pozos playeros, galerías filtrantes) que usa la arena como prefiltro.', vars: 'Caudal de toma (Qtoma), velocidad de aproximación, profundidad, área de rejilla.', units: 'm³/h; m/s; m; m².', rel: 'A mayor caudal, mayor velocidad de aproximación y mayor riesgo de arrastrar organismos (impingement y entrainment). Una toma profunda suele captar agua más fría y menos turbia.', ex: 'Reducir la velocidad en las rejillas protege larvas y peces jóvenes (' + SIM_NOTE + ')', limits: 'Se representa la protección ecológica con un índice simplificado de riesgo, no con un modelo poblacional.', error: 'Creer que captar más caudal siempre mejora la producción.', src: SRC.faoDesal, use: 'Nivel 01: eliges profundidad, caudal y rejillas; el arrecife cercano reacciona.' },
  { id: 'pretratamiento', sec: 'agua', title: 'Pretratamiento', def: 'Conjunto de etapas antes de las membranas: cribado (rejillas), coagulación–floculación, filtración (arena, cartuchos o ultrafiltración) y, a veces, ajuste químico. Protege las membranas; no desaliniza.', vars: 'Diferencial de presión del filtro (ΔP), turbidez de salida, SDI, dosis de coagulante (abstracta).', units: 'bar; NTU; adimensional.', rel: 'ΔP aumenta a medida que el filtro retiene sólidos; al superar el límite, se lava a contracorriente o se reduce el caudal.', ex: 'Un filtro con ΔP de 1,2 bar y límite de 1,0 bar requiere lavado o menos carga (' + SIM_NOTE + ')', limits: 'La química de coagulación es abstracta y no ofrece dosis reales.', error: 'Confundir pretratamiento con desalinización.', src: SRC.pnnl, use: 'Nivel 01 y Calima: gestionas la carga de sólidos y el lavado de filtros.' },
  { id: 'incertidumbre_med', sec: 'agua', title: 'Incertidumbre de medición', def: 'Todo sensor informa un valor con un rango de error. Ubicación, calibración, ensuciamiento del sensor y variabilidad natural afectan la lectura.', vars: 'Valor medido, incertidumbre (±), deriva.', units: 'Las de la variable medida.', rel: 'Dos lecturas solo son distinguibles si su diferencia supera la incertidumbre combinada.', ex: 'Turbidez 12 ± 3 NTU frente a 14 ± 3 NTU: no hay evidencia de diferencia (' + SIM_NOTE + ')', limits: 'La incertidumbre simulada es gaussiana y fija por sensor.', error: 'Tratar una lectura única como verdad exacta, o descartar el conocimiento local que contradice al sensor.', src: 'Metrología general (GUM, JCGM 100:2008).', use: 'Barrido Sensorial: cada muestra muestra su ±. Tía Marea detecta un sensor mal ubicado.' },
  /* ---------------- DESALINIZACIÓN ---------------- */
  { id: 'osmosis', sec: 'desal', title: 'Ósmosis y presión osmótica', def: 'El agua tiende a pasar a través de una membrana semipermeable desde la solución diluida hacia la concentrada. La presión que detiene ese flujo es la presión osmótica (π).', vars: 'π, concentración (C), temperatura (T).', units: 'bar; g/L; K.', rel: 'π crece casi en proporción a la concentración de sales: para agua de mar típica ronda 25–28 bar. En el juego: π ≈ 0,77 bar·L/g × C.', ex: 'Alimentación 35 g/L → π ≈ 27 bar; concentrado 60 g/L → π ≈ 46 bar.', limits: 'Relación lineal (tipo van \'t Hoff) válida como aproximación pedagógica.', error: 'Pensar que la membrana "destruye" la sal.', src: SRC.elimelech, use: 'Nivel 02: el corte de membrana animado muestra moléculas de agua cruzando e iones rebotando.' },
  { id: 'ro', sec: 'desal', title: 'Ósmosis inversa (OI)', def: 'Se aplica una presión mayor que la osmótica para forzar el agua a pasar por la membrana hacia el lado diluido. Se separan dos corrientes: permeado (baja salinidad) y concentrado o salmuera (alta salinidad).', vars: 'Presión de alimentación (P), presión neta de impulso (NDP), flujo de permeado (Qp).', units: 'bar; bar; m³/h.', rel: 'NDP ≈ P − π_media − pérdidas. Sin NDP positiva no hay permeado. Más presión aumenta el flujo, pero también la energía, el riesgo mecánico y el ensuciamiento.', ex: 'Con P = 60 bar y π_media = 37 bar, la NDP ≈ 21 bar (' + SIM_NOTE + ')', limits: 'Un solo elemento promedio; no se modelan etapas ni polarización por concentración en detalle.', error: 'Creer que más presión siempre produce una operación mejor o más segura.', src: SRC.pnnl, use: 'Tejedor de Presión: regulas presión y recuperación dentro de límites seguros.' },
  { id: 'recuperacion', sec: 'desal', title: 'Recuperación (R)', def: 'Fracción del caudal de alimentación que sale como permeado.', vars: 'Qf (alimentación), Qp (permeado), Qc (concentrado).', units: 'm³/h; R en % o fracción.', rel: 'Qf = Qp + Qc;  R = Qp / Qf. Si R sube con la misma alimentación, Qc baja y la sal se concentra: Cc ≈ Cf / (1 − R) (si Cp es pequeño).', ex: 'Qf = 100 m³/h, Qp = 42 m³/h → R = 42 %, Qc = 58 m³/h.', limits: 'La recuperación máxima real depende de incrustación, presión máxima y calidad.', error: 'Asumir que una recuperación del 100 % es deseable o posible.', src: SRC.pnnl, use: 'Niveles 02 y 03: la recuperación que eliges reaparece en la salmuera.' },
  { id: 'balance_sal', sec: 'desal', title: 'Balance de sal', def: 'La masa de sal que entra debe salir: casi toda va al concentrado.', vars: 'Cf, Cp, Cc; Qf, Qp, Qc.', units: 'g/L y m³/h → kg/h (1 g/L · 1 m³/h = 1 kg/h).', rel: 'Cf·Qf ≈ Cp·Qp + Cc·Qc.', ex: '35 g/L × 100 m³/h = 3 500 kg/h de sal; 0,3 × 42 = 12,6 kg/h salen en el permeado; ≈ 3 487 kg/h salen en 58 m³/h de concentrado → Cc ≈ 60 g/L.', limits: 'Balance en estado estacionario; ignora acumulación en membranas.', error: 'Ignorar el concentrado o pensar que la sal desaparece.', src: 'Conservación de la masa (principio físico).', use: 'Lente Nexo en la planta: las flechas de sal suman siempre lo mismo.' },
  { id: 'sec', sec: 'desal', title: 'Consumo específico de energía (SEC)', def: 'Energía eléctrica usada por cada metro cúbico de permeado.', vars: 'Potencia (P_el), caudal de permeado (Qp), energía (E).', units: 'kW; m³/h; kWh/m³.', rel: 'SEC = Energía / Volumen = P_el / Qp. Bombeo: P_hid ≈ P(bar) × Qf(m³/h) / 36 (kW); la recuperación de energía del concentrado reduce el consumo.', ex: '150 kW / 42 m³/h ≈ 3,57 kWh/m³. Plantas de OI de agua de mar suelen reportar del orden de 3–4 kWh/m³ en total; el mínimo termodinámico a 50 % de recuperación ≈ 1,06 kWh/m³.', limits: 'El juego usa eficiencias de bomba y recuperador fijas (' + SIM_NOTE + ')', error: 'Confundir potencia (kW) con energía específica (kWh/m³).', src: SRC.voutchkov + ' ' + SRC.elimelech, use: 'Nivel 02: el panel de energía calcula SEC en vivo.' },
  { id: 'fouling', sec: 'desal', title: 'Ensuciamiento (fouling) e incrustación (scaling)', def: 'Ensuciamiento: depósito de partículas, materia orgánica o biopelícula sobre la membrana. Incrustación: precipitación de sales poco solubles cuando el concentrado se sobresatura.', vars: 'Índice de ensuciamiento, ΔP del tren, conductividad del permeado, índice de incrustación.', units: 'adimensional; bar; µS/cm.', rel: 'Más turbidez y menos pretratamiento → más fouling. Más recuperación → mayor concentración → más riesgo de scaling. Ambos reducen el flujo y empeoran la calidad.', ex: 'La limpieza química restituye parte del desempeño, con costo y tiempo fuera de servicio (' + SIM_NOTE + ')', limits: 'Índices agregados; no se modela química de antiincrustantes.', error: 'Limpiar "por si acaso" sin indicadores que lo justifiquen, o nunca limpiar.', src: SRC.pnnl, use: 'OSMORA y Scale Wisp se alimentan de límites forzados.' },
  { id: 'erd', sec: 'desal', title: 'Recuperación de energía (ERD)', def: 'Dispositivo que transfiere la presión del concentrado (que sale aún presurizado) a una parte de la alimentación, reduciendo el trabajo de la bomba de alta presión.', vars: 'Eficiencia del ERD (η_ERD), presión del concentrado.', units: '%; bar.', rel: 'Energía recuperable ≈ η_ERD × P × Qc. Sincronizar el ERD evita pérdidas y golpes de presión.', ex: 'Con η_ERD = 95 %, el SEC baja de forma notable frente a no recuperar (' + SIM_NOTE + ')', limits: 'Representado como un factor de recuperación; no hay dinámica de rotor.', error: 'Pensar que el ERD "crea" energía.', src: SRC.voutchkov, use: 'Minijuego de sincronización del recuperador en el Laberinto Osmótico.' },
  { id: 'permeado', sec: 'desal', title: 'Calidad del permeado y remineralización', def: 'El permeado de OI tiene muy pocas sales: es corrosivo, puede carecer de calcio y magnesio y conservar boro. Para consumo o riego se ajusta (remineralización, mezcla, segunda etapa).', vars: 'Conductividad del permeado, boro, dureza, pH.', units: 'µS/cm; mg/L; mg/L CaCO3; pH.', rel: 'Claridad visual no implica especificación: un agua cristalina puede estar fuera de límite.', ex: 'El tren B produjo permeado claro con conductividad sobre el límite: LIMEN lo aisló (' + SIM_NOTE + ')', limits: 'Límites del juego son supuestos; la normativa real depende del país y uso.', error: 'Evaluar la calidad por apariencia; asumir que el agua desalinizada sirve igual para cualquier uso.', src: SRC.faoDesal, use: 'Nivel 02: Naira detiene el envío de permeado a cultivos.' },
  /* ---------------- SALMUERA ---------------- */
  { id: 'salmuera', sec: 'salmuera', title: 'Salmuera (concentrado)', def: 'Corriente de rechazo de la OI con más sal que el agua de mar, posible temperatura distinta y residuos químicos del proceso.', vars: 'Caudal de concentrado (Qc), salinidad (Cc), temperatura, densidad.', units: 'm³/h; g/L; °C; kg/m³.', rel: 'Al ser más densa, tiende a hundirse y extenderse por el fondo; su impacto depende de caudal, dilución, corrientes, marea y receptores sensibles.', ex: 'Qc = 58 m³/h a 60 g/L frente a mar ambiente de 35 g/L (' + SIM_NOTE + ')', limits: 'La pluma se simula en 2D con advección–difusión simplificada.', error: 'Considerar la salmuera un residuo inocuo.', src: SRC.faoDesal, use: 'Brújula de Salmuera: ves la pluma y el balance de masa.' },
  { id: 'dilucion', sec: 'salmuera', title: 'Diluir no elimina masa', def: 'Mezclar salmuera con más agua reduce la concentración en un punto, pero la masa total de sal se conserva y se reparte en un volumen mayor.', vars: 'Masa de sal (m), volumen (V), concentración (C).', units: 'kg; m³; kg/m³ = g/L.', rel: 'm = C·V. Si V se multiplica por 10, C se divide por 10 (respecto al exceso), pero m no cambia.', ex: '1 m³ a 60 g/L contiene 60 kg de sal; mezclado en 10 m³ sigue habiendo 60 kg más la sal del agua de mezcla.', limits: 'No se modelan reacciones químicas.', error: 'Creer que diluir hace desaparecer la sal.', src: 'Conservación de la masa.', use: 'Salt Mirage se disuelve cuando lo explicas.' },
  { id: 'descarga', sec: 'salmuera', title: 'Descarga, difusores y monitoreo', def: 'La descarga controlada usa difusores que aumentan la mezcla inicial, ventanas de marea favorables y monitoreo de receptores (praderas marinas, manglares, arrecifes).', vars: 'Exceso de salinidad (ΔS), área de impacto, tiempo de exposición, marea.', units: 'g/L; m²; h.', rel: 'El impacto acumulativo depende de duración y trayectoria, no solo del punto de salida.', ex: 'Descargar con marea saliente y difusor reduce el área con ΔS > 2 g/L (' + SIM_NOTE + ')', limits: 'Umbral ecológico del juego (ΔS = 2 g/L) es un supuesto; los umbrales reales dependen de especies y normativa.', error: 'Trasladar el problema "fuera de pantalla" y darlo por resuelto.', src: SRC.faoDesal, use: 'La Pluma Invisible: debes contener la exposición, no esconderla.' },
  { id: 'valorizacion', sec: 'salmuera', title: 'Valorización de minerales: límites', def: 'Extraer sales o minerales de la salmuera es posible, pero su rentabilidad depende de concentraciones, energía, mercado, escala, pureza y gestión de residuos secundarios.', vars: 'Energía de concentración, rendimiento, precio, costo.', units: 'kWh/t; t/año; USD/t.', rel: 'Concentrar más requiere energía; la valorización puede reducir el volumen pero no siempre el impacto total.', ex: 'Un estanque de evaporación pequeño produce sal artesanal, pero ocupa área y depende del clima (' + SIM_NOTE + ')', limits: 'El juego no ofrece análisis de mercado real.', error: 'Asumir que toda valorización mineral es rentable o "cero impacto".', src: SRC.faoDesal, use: 'Misión: "Cristales que no pagan la cuenta".' },
  /* ---------------- SOLAR ---------------- */
  { id: 'irradiancia', sec: 'solar', title: 'Irradiancia (GHI)', def: 'Potencia solar por unidad de área que llega a una superficie horizontal. Cambia con la hora, las nubes, el polvo y la estación. No es temperatura.', vars: 'GHI, irradiancia de referencia (G_ref = 1 000 W/m² en STC).', units: 'W/m² (potencia); kWh/m²·día (energía).', rel: 'P_FV ≈ P_nom · (G / G_ref) · derating.', ex: 'Una nube que cubre un string reduce G de 950 a 300 W/m² en segundos (' + SIM_NOTE + ')', limits: 'Modelo lineal; ignora el espectro y el ángulo de incidencia en detalle.', error: 'Confundir irradiancia con temperatura.', src: SRC.ideam, use: 'Dunas Fotónicas: las sombras de nubes reales del escenario modifican la generación.' },
  { id: 'kw_kwh', sec: 'solar', title: 'Potencia (kW) frente a energía (kWh)', def: 'La potencia es un ritmo instantáneo; la energía es potencia acumulada en el tiempo.', vars: 'P(t), E.', units: 'kW; kWh. 1 kW durante 1 h = 1 kWh.', rel: 'E = Σ P·Δt (área bajo la curva de potencia).', ex: 'Un pico de 600 kW durante 15 minutos aporta 150 kWh, no 600 kWh.', limits: '—', error: 'Asumir que una potencia pico garantiza energía suficiente para el día o la noche.', src: 'Física básica de energía.', use: 'El Espejismo de Mediodía y el Peak Sprite.' },
  { id: 'derating', sec: 'solar', title: 'Temperatura, suciedad y sombra', def: 'Factores que reducen la producción fotovoltaica respecto a la nominal: alta temperatura de módulo, polvo acumulado, sombras parciales, pérdidas del inversor y disponibilidad.', vars: 'Temperatura de módulo, factor de suciedad, factor de sombra, eficiencia del inversor.', units: '°C; fracciones (0–1).', rel: 'La potencia baja ≈ 0,3–0,5 % por cada °C sobre 25 °C (coeficiente típico de fichas técnicas). Limpiar consume agua: hay un trade-off.', ex: 'Polvo del 12 % y módulo a 60 °C reducen la potencia a ~75 % de la nominal (' + SIM_NOTE + ')', limits: 'Factores multiplicativos independientes.', error: 'Creer que los paneles producen lo mismo todo el día o que limpiar no cuesta nada.', src: 'Fichas técnicas de módulos FV (coeficiente de temperatura). ' + SRC.ideam, use: 'Misiones "Panel bajo sombra" y "Agua para limpiar o producir".' },
  /* ---------------- EÓLICA ---------------- */
  { id: 'curva_potencia', sec: 'eolica', title: 'Curva de potencia de un aerogenerador', def: 'Relación entre velocidad del viento y potencia eléctrica entregada. Tiene cuatro regiones: bajo cut-in (no produce), región parcial (crece rápido), nominal (meseta) y sobre cut-out (parada de seguridad).', vars: 'v, cut-in, v_rated, cut-out, P_nom.', units: 'm/s; kW.', rel: 'En la región parcial la potencia disponible crece aproximadamente con v³ (P = ½ρAv³Cp), pero la turbina se limita a P_nom y se detiene sobre cut-out.', ex: 'Turbina del juego: cut-in 3 m/s, nominal 12 m/s, cut-out 25 m/s (valores típicos; ' + SIM_NOTE + ')', limits: 'Curva por tramos; densidad del aire constante.', error: 'Extrapolar v³ por encima de la potencia nominal; creer que más viento siempre es mejor.', src: 'Valores típicos de curvas de fabricantes; ' + SRC.upme, use: 'Ráfaga Umbral y Gust Loop.' },
  { id: 'estela', sec: 'eolica', title: 'Efecto estela', def: 'Detrás de una turbina el viento es más lento y turbulento. Las turbinas alineadas con la dirección del viento pierden producción si están muy cerca.', vars: 'Distancia entre turbinas (en diámetros), pérdida por estela.', units: 'D (diámetros de rotor); %.', rel: 'A mayor separación en la dirección dominante, menor pérdida.', ex: 'Una turbina a 3 D detrás de otra recibe ~70 % de la velocidad libre (' + SIM_NOTE + ')', limits: 'Modelo de déficit lineal simple.', error: 'Ignorar estelas al distribuir turbinas.', src: 'Modelos de estela tipo Jensen (literatura eólica).', use: 'Misión "Turbinas en estela".' },
  { id: 'pronostico', sec: 'eolica', title: 'Pronóstico e incertidumbre', def: 'Un pronóstico es una estimación con banda de incertidumbre. Los eventos extremos son poco frecuentes pero reales; eliminarlos del entrenamiento sesga el modelo.', vars: 'Valor esperado, banda (p10–p90), error de pronóstico.', units: 'las de la variable.', rel: 'Decidir con la banda (no solo con el promedio) permite reservar ante escenarios desfavorables.', ex: 'Viento pronosticado 10 ± 4 m/s; una ráfaga real de 27 m/s estaba fuera del modelo porque se borró como "ruido".', limits: 'Bandas simuladas.', error: 'Tratar los extremos como ruido.', src: 'Práctica de pronóstico probabilístico.', use: 'Nivel 05: la etiqueta OUTLIER_CLEAN.' },
  { id: 'complementariedad', sec: 'eolica', title: 'Complementariedad solar–eólica', def: 'En muchas costas áridas el viento sopla más de noche o en otra estación que el pico solar. Combinar fuentes reduce la variabilidad, pero no la elimina.', vars: 'Perfiles horarios FV y eólico, correlación.', units: 'kW; adimensional.', rel: 'Menor correlación entre fuentes → menos horas de déficit para la misma capacidad.', ex: 'En Aridia el viento se intensifica al atardecer (' + SIM_NOTE + ')', limits: 'Perfiles sintéticos.', error: 'Asumir que toda energía renovable está disponible de forma constante.', src: SRC.upme, use: 'Microred de los niveles 04–06.' },
  /* ---------------- ALMACENAMIENTO ---------------- */
  { id: 'bess', sec: 'almac', title: 'Batería (BESS): capacidad, potencia y SOC', def: 'Sistema que almacena energía eléctrica para usarla después. Capacidad (kWh) es cuánta energía guarda; potencia (kW) es qué tan rápido puede cargarse o descargarse; SOC es la fracción de carga.', vars: 'E_cap, P_charge, P_discharge, SOC, SOC_min, SOC_max.', units: 'kWh; kW; %.', rel: 'SOC(t+1) = SOC(t) + η_c·P_c·Δt/E_cap − P_d·Δt/(η_d·E_cap), con SOC_min ≤ SOC ≤ SOC_max.', ex: '1 000 kWh, 250 kW: puede entregar 250 kW durante ~4 h (menos pérdidas).', limits: 'Degradación simplificada por ciclos equivalentes.', error: 'Tratar la batería como fuente primaria; asumir eficiencia del 100 %.', src: 'Modelo estándar de balance de energía en baterías.', use: 'Cambio de Reserva y BETA-9.' },
  { id: 'eficiencia_bess', sec: 'almac', title: 'Eficiencia y pérdidas', def: 'Cargar y descargar pierde energía como calor. La eficiencia de ida y vuelta de baterías de ion-litio suele estar en el rango 85–95 %.', vars: 'η_c, η_d, η_rt = η_c·η_d.', units: '%.', rel: 'Ciclar innecesariamente (cargar y descargar en el mismo periodo) desperdicia energía y desgasta la batería.', ex: 'η_c = η_d = 0,95 → η_rt ≈ 90 % (' + SIM_NOTE + ')', limits: 'Eficiencias constantes.', error: 'Ignorar pérdidas y degradación.', src: 'Rangos típicos de la literatura técnica sobre almacenamiento.', use: 'Detección de ciclos ineficientes en la Bóveda.' },
  { id: 'reserva', sec: 'almac', title: 'Reserva mínima y cargas críticas', def: 'Energía que se protege para servicios esenciales (agua potable, salud, comunicaciones, seguridad) ante eventos inciertos. Su valor depende de cuándo podrá usarse.', vars: 'SOC_reserva, carga crítica, duración del evento.', units: '%; kW; h.', rel: 'Energía de reserva ≥ carga crítica × duración / η_d.', ex: 'Carga crítica 120 kW durante 3 h → ≈ 380 kWh de reserva (' + SIM_NOTE + ')', limits: 'Prioridades definidas por el escenario.', error: 'Usar toda la reserva antes de un evento incierto para mejorar un indicador de corto plazo.', src: 'Práctica de operación de microredes.', use: 'El Devorador de Reserva.' },
  { id: 'blackstart', sec: 'almac', title: 'Arranque en negro (abstracto)', def: 'Recuperar una red tras un apagón energizando primero una fuente estable (p. ej., la batería) y reconectando cargas por etapas, de las críticas a las flexibles.', vars: 'Orden de reconexión, potencia disponible.', units: 'kW.', rel: 'Reconectar todo a la vez puede superar la potencia disponible y causar otra caída.', ex: 'Secuencia: BESS → servicios esenciales → bombeo de agua → RO → riego → electrolizador.', limits: 'Representación conceptual, no instrucciones de operación real.', error: 'Reconectar cargas grandes primero.', src: 'Conceptos de operación de microredes.', use: 'Nivel 06: minijuego de reconexión por etapas.' },
  /* ---------------- HIDRÓGENO ---------------- */
  { id: 'electrolisis', sec: 'h2', title: 'Electrólisis del agua', def: 'Uso de electricidad para separar agua purificada en hidrógeno (cátodo) y oxígeno (ánodo). Tecnologías: alcalina, PEM y óxido sólido.', vars: 'Energía al electrolizador, SEC_H2, masa de H2.', units: 'kWh; kWh/kg; kg.', rel: 'm_H2 ≈ E / SEC_H2. Los sistemas actuales suelen requerir del orden de 50–55 kWh por kg de H2 (sistema completo).', ex: '5 500 kWh / 55 kWh/kg ≈ 100 kg de H2 (' + SIM_NOTE + ')', limits: 'SEC constante; sin dinámica térmica ni degradación de stack.', error: 'Confundir energía almacenada con eficiencia; pensar que el H2 "produce" energía.', src: SRC.doeElec + ' ' + SRC.doeShot + ' ' + SRC.irenaStrat, use: 'Sincronizador H2 en la Ciudadela.' },
  { id: 'h2_vector', sec: 'h2', title: 'El hidrógeno es un vector, no una fuente', def: 'El hidrógeno no se extrae listo como energía primaria: se produce gastando energía y luego puede almacenarse o transportarse. Al usarlo se recupera solo parte de esa energía.', vars: 'Poder calorífico (LHV ≈ 33,3 kWh/kg), eficiencias de conversión.', units: 'kWh/kg; %.', rel: 'Electricidad → H2 → electricidad suele recuperar una fracción menor que una batería.', ex: '55 kWh por kg producido frente a 33,3 kWh/kg de contenido energético (LHV).', limits: 'No se modelan celdas de combustible.', error: 'Confundir hidrógeno con fuente primaria de energía.', src: 'LHV del H2 (propiedad física). ' + SRC.iea, use: 'Debate del contrato de excedente.' },
  { id: 'h2_agua', sec: 'h2', title: 'Agua para producir hidrógeno', def: 'La estequiometría exige unos 8,9 kg de agua por kg de H2. El retiro real es mayor por purificación (rechazo de OI), enfriamiento y pérdidas.', vars: 'Agua estequiométrica, agua total, rechazo de purificación.', units: 'kg/kg H2; L/kg H2.', rel: 'Agua_total = agua_estequiométrica + rechazo + enfriamiento + pérdidas.', ex: '100 kg H2 → ≥ 894 kg de agua ultrapura; con purificación y enfriamiento puede requerir varias veces más (' + SIM_NOTE + ')', limits: 'Factores de retiro configurables.', error: 'Ignorar el agua de proceso en una región árida.', src: SRC.stoich + ' ' + SRC.irenaWater, use: 'Misión "Agua ultrapura".' },
  { id: 'h2_verde', sec: 'h2', title: '¿Qué hace "verde" al hidrógeno?', def: 'El atributo depende del origen de la electricidad, la frontera de análisis (qué emisiones se cuentan) y la operación temporal (coincidencia horaria con generación renovable).', vars: 'Origen eléctrico, intensidad de emisiones, periodo de coincidencia.', units: 'kg CO2e/kg H2; h.', rel: 'Electrólisis con electricidad fósil no es verde aunque el proceso sea el mismo.', ex: 'Operar de noche con diésel convierte el lote en no verde (' + SIM_NOTE + ')', limits: 'Certificación simplificada.', error: 'Afirmar que todo H2 por electrólisis es automáticamente verde.', src: SRC.irenaStrat + ' ' + SRC.minenergia, use: 'Greenwash Phantom.' },
  { id: 'h2_seguridad', sec: 'h2', title: 'Seguridad: protocolo abstracto', def: 'El hidrógeno es inflamable en un rango amplio de concentraciones en aire, se dispersa rápido y su llama es poco visible. Ante una condición insegura se sigue un protocolo, nunca la improvisación.', vars: 'Detección, aislamiento, ventilación, verificación.', units: '—', rel: 'DETECTAR → AISLAR → DETENER → VENTILAR → VERIFICAR → AUTORIZAR REINICIO.', ex: 'La Llama que No se Ve: se resuelve con el protocolo, no con valentía.', limits: 'Representación conceptual; no son instrucciones operativas.', error: 'Puentear sensores o reiniciar sin verificar.', src: SRC.doeElec, use: 'Nivel 07 y Calima.' },
  { id: 'oxigeno', sec: 'h2', title: 'El oxígeno subproducto', def: 'La electrólisis libera ~8 kg de O2 por kg de H2. Venderlo requiere purificación, compresión, demanda cercana y logística.', vars: 'Masa de O2, demanda, costo de manejo.', units: 'kg.', rel: 'No es un ingreso garantizado.', ex: 'Sin comprador cercano, el O2 se ventea de forma segura (' + SIM_NOTE + ')', limits: '—', error: 'Considerar el oxígeno un ingreso garantizado.', src: SRC.stoich, use: 'Misión "El oxígeno prometido".' },
  /* ---------------- AGROECOLOGÍA ---------------- */
  { id: 'etc', sec: 'agro', title: 'Evapotranspiración del cultivo (ETc)', def: 'Agua que un cultivo pierde por evaporación del suelo y transpiración. Se estima a partir de la evapotranspiración de referencia (ET0) y un coeficiente de cultivo (Kc) que cambia con la etapa.', vars: 'ET0, Kc, ETc.', units: 'mm/día (1 mm sobre 1 m² = 1 L).', rel: 'ETc = Kc · ET0.', ex: 'ET0 = 6 mm/día, Kc (tomate, etapa media) ≈ 1,15 → ETc ≈ 6,9 mm/día.', limits: 'Kc de tablas generales; el juego no ajusta por clima local detallado.', error: 'Regar según calendario fijo sin considerar etapa ni clima.', src: SRC.fao56, use: 'Mapa de Raíces en el Oasis.' },
  { id: 'riego_bruto', sec: 'agro', title: 'Necesidad bruta y eficiencia de riego', def: 'La necesidad neta es el agua que debe llegar a la raíz; la bruta incluye pérdidas del sistema (evaporación, escorrentía, percolación).', vars: 'Necesidad neta, eficiencia de aplicación.', units: 'mm; fracción.', rel: 'Agua_bruta = Necesidad_neta / eficiencia. Goteo con cobertura suele ser más eficiente que inundación.', ex: '6,9 mm netos con goteo (0,9) → 7,7 mm brutos; con inundación (0,6) → 11,5 mm (' + SIM_NOTE + ')', limits: 'Eficiencias típicas, no medidas de campo.', error: 'Evaluar solo volumen y no calidad ni distribución.', src: SRC.fao56, use: 'Misión "Goteo al amanecer".' },
  { id: 'calidad_riego', sec: 'agro', title: 'Calidad de agua para riego: EC, SAR, boro', def: 'La salinidad (ECw) reduce la disponibilidad de agua para la planta; el SAR relaciona sodio con calcio y magnesio y afecta la infiltración del suelo; el boro es tóxico por encima de umbrales que dependen del cultivo.', vars: 'ECw, SAR, boro, pH, cloruros.', units: 'dS/m; adimensional; mg/L; pH.', rel: 'Según guías de FAO, ECw < 0,7 dS/m suele no restringir el uso; 0,7–3,0 restricción ligera a moderada; > 3,0 severa. Un agua muy pura (EC baja) con SAR alto puede dañar la infiltración. Umbrales dependen de especie, etapa, suelo, drenaje y clima.', ex: 'Permeado de OI: EC muy baja, puede conservar boro y requiere remineralización o mezcla.', limits: 'El juego usa umbrales orientativos, no reglas universales.', error: 'Asumir que el agua potable siempre es ideal para riego.', src: SRC.fao29 + ' ' + SRC.faoDesal, use: 'La Cosecha Transparente.' },
  { id: 'lavado', sec: 'agro', title: 'Sales en el suelo y fracción de lavado', def: 'Con riego en clima árido las sales se acumulan en la zona de raíces. Una fracción del agua aplicada debe drenar para "lavar" sales, si el drenaje lo permite.', vars: 'EC del suelo (ECe), fracción de lavado (LF), drenaje.', units: 'dS/m; fracción.', rel: 'Más volumen sin drenaje no corrige el problema y puede empeorarlo.', ex: 'Aumentar riego sin corregir calidad ni drenaje produce encharcamiento y estrés (' + SIM_NOTE + ')', limits: 'Balance de sales en un solo compartimento.', error: 'Responder al estrés salino solo con más agua.', src: SRC.fao29, use: 'Estado de error seguro del Nivel 08.' },
  { id: 'productividad', sec: 'agro', title: 'Productividad hídrica (WP)', def: 'Producción útil por unidad de agua utilizada.', vars: 'Producción, agua aplicada.', units: 'kg/m³.', rel: 'WP = producción útil / agua utilizada. Un rendimiento alto con mucha agua puede tener baja WP.', ex: '2 400 kg con 800 m³ → WP = 3 kg/m³ (' + SIM_NOTE + ')', limits: 'No captura nutrición, cultura alimentaria ni servicios ecosistémicos: por eso el juego usa varios criterios.', error: 'Premiar únicamente el mayor rendimiento.', src: SRC.fao56, use: 'Panel del Oasis.' },
  { id: 'agroeco10', sec: 'agro', title: 'Los 10 elementos de la agroecología', def: 'Diversidad, sinergias, eficiencia, reciclaje, resiliencia, co-creación e intercambio de conocimientos, valores humanos y sociales, cultura y tradiciones alimentarias, gobernanza responsable, y economía circular y solidaria.', vars: 'Diversidad de especies, salud del suelo, participación, aceptación comunitaria.', units: 'índices cualitativos y cuantitativos.', rel: 'La agroecología no es una lista fija de técnicas: integra dimensiones ecológicas, sociales y de gobernanza.', ex: 'Asociar maíz–frijol–ahuyama y sembrar corredores de flores atrae polinizadores y protege el suelo.', limits: 'El juego representa algunos elementos con indicadores simplificados.', error: 'Reducir la agroecología a eficiencia técnica o a decoración.', src: SRC.fao10, use: 'Naira y el banco de semillas.' },
  { id: 'cobertura', sec: 'agro', title: 'Cobertura (mulch) y biodiversidad', def: 'Cubrir el suelo con residuos vegetales reduce evaporación, temperatura del suelo y erosión; los corredores de biodiversidad sostienen polinizadores y controladores naturales.', vars: 'Fracción cubierta, temperatura de suelo, diversidad.', units: '%; °C; nº de especies.', rel: 'Menos evaporación del suelo → menor necesidad bruta de agua.', ex: 'Cobertura del 70 % reduce la evaporación del suelo en la simulación (' + SIM_NOTE + ')', limits: 'Efectos agregados.', error: 'Ver la cobertura como desorden en lugar de infraestructura viva.', src: SRC.fao56 + ' ' + SRC.fao10, use: 'Misión "Corredor polinizador".' },
  /* ---------------- STEAM ---------------- */
  { id: 'indagacion', sec: 'steam', title: 'Ciclo de indagación', def: 'Observar → preguntar → medir → proponer hipótesis → modelar → prototipar → ejecutar → observar consecuencias → depurar → explicar → transferir.', vars: '—', units: '—', rel: 'Cada nivel del juego sigue este ciclo.', ex: 'En la toma: observar el color del agua, medir turbidez, hipotetizar el pulso, ajustar el caudal.', limits: '—', error: 'Saltar de la observación a la conclusión sin medir.', src: SRC.unesco, use: 'Estructura de todos los capítulos.' },
  { id: 'gemelo', sec: 'steam', title: 'Gemelo digital', def: 'Modelo computacional conectado a datos de un sistema real para predecir y optimizar. Es útil si declara sus supuestos, su incertidumbre y lo que no modela.', vars: 'Variables modeladas, datos de entrenamiento, función objetivo, restricciones.', units: '—', rel: 'Un modelo responde con precisión la pregunta que se le formula; si la pregunta (objetivo) es incompleta, la respuesta también.', ex: 'MIRAGE maximizaba excedente exportable sujeto a mínimos modelados con datos incompletos.', limits: '—', error: 'Confundir el modelo con el territorio.', src: SRC.unesco, use: 'MIRAGE y MOSAICO.' },
  { id: 'causalidad', sec: 'steam', title: 'Correlación no es causalidad', def: 'Dos variables pueden moverse juntas sin que una cause a la otra (una tercera variable, coincidencia o causalidad inversa).', vars: '—', units: '—', rel: 'Para inferir causa: mecanismo plausible + secuencia temporal + control de otras variables + experimento cuando es posible.', ex: 'LIMEN aparece antes de cada fallo: ¿los causa o los anticipa?', limits: '—', error: 'Culpar a quien aparece cerca del problema.', src: SRC.unesco, use: 'El misterio de LIMEN.' },
  { id: 'incertidumbre', sec: 'steam', title: 'La incertidumbre no es ignorancia', def: 'Declarar rangos, supuestos y escenarios permite decisiones robustas y discutibles.', vars: 'Rango, probabilidad, escenario.', units: '—', rel: 'Una política robusta funciona aceptablemente en varios escenarios, no solo en el promedio.', ex: 'MOSAICO: "Tres escenarios son viables. Ninguno es óptimo para todos los criterios."', limits: '—', error: 'Presentar un único número como certeza.', src: SRC.unesco, use: 'Final de la historia.' },
  /* ---------------- ECONOMÍA ---------------- */
  { id: 'lcoe', sec: 'econ', title: 'Costos nivelados (LCOE, LCOH, LCOA)', def: 'Costo total del ciclo de vida (inversión + operación) dividido por la producción total a lo largo de la vida útil, descontada en el tiempo.', vars: 'Inversión, O&M, tasa de descuento, producción anual, vida útil.', units: 'USD/kWh (energía), USD/kg (H2), USD/m³ (agua).', rel: 'LCO ≈ Σ costos descontados / Σ producción descontada. Operar pocas horas eleva el costo nivelado.', ex: 'Un electrolizador con pocas horas de excedente tiene LCOH más alto (' + SIM_NOTE + ')', limits: 'Cálculo simplificado; no es asesoría financiera.', error: 'Creer que el menor costo es siempre la mejor decisión.', src: SRC.irenaStrat, use: 'Observatorio económico de la Mesa del Nexo.' },
  { id: 'multiobjetivo', sec: 'econ', title: 'Decisión multiobjetivo y frente de Pareto', def: 'Cuando hay varios criterios en conflicto, una alternativa es dominada si otra es igual o mejor en todos y estrictamente mejor en al menos uno. Las no dominadas forman el frente de Pareto.', vars: 'Criterios normalizados, pesos, alternativas.', units: 'adimensional tras normalizar.', rel: 'Los pesos expresan valores y prioridades: son decisiones discutibles, no hechos científicos. Sumar unidades distintas sin normalizar no tiene sentido.', ex: 'Tres escenarios viables; ninguno es óptimo para todos.', limits: 'Normalización min–max en el juego.', error: 'Ocultar ponderaciones dentro de una puntuación única.', src: 'Teoría de decisión multicriterio.', use: 'Tablero Mosaico y MonoScore.' },
  { id: 'gobernanza', sec: 'econ', title: 'Gobernanza y justicia distributiva', def: 'Quién decide, con qué información, quién asume los costos y quién recibe los beneficios. La participación de las comunidades mejora los objetivos y la legitimidad.', vars: 'Participación, transparencia, equidad de acceso.', units: 'cualitativas e índices.', rel: 'Una decisión transparente puede discutirse; una opaca solo puede obedecerse.', ex: 'El consejo incluye comunidades, operación, agricultura y ambiente.', limits: 'Representación narrativa y con índices simplificados.', error: 'Tratar a las comunidades como receptoras pasivas.', src: SRC.fao10, use: 'La Mesa del Nexo y el epílogo.' },
];
// Personajes
const CODEX_PEOPLE = [
  ['p_amaya', 'Amaya Serrano', 'Estudiante de sistemas energéticos y programación. Brillante, impaciente y competitiva consigo misma. Cuando se pone nerviosa, convierte problemas técnicos en analogías culinarias. Quiere demostrar que su controlador predictivo puede coordinar SYNARA.'],
  ['p_kiru', 'KIRU', 'Robot inspirado en un zorro del desierto y una lagartija: orejas solares, cola con microturbina, patas magnéticas y un compartimento de muestras. Hablador, teatral, valiente e incapaz de susurrar. Teme ser solo un dispositivo reemplazable.'],
  ['p_naira', 'Naira Valdés', 'Agroecóloga y guardiana del banco de semillas. Serena, irónica y poco impresionable ante interfaces brillantes. "Una gráfica puede estar muy limpia y seguir sin conocer una raíz."'],
  ['p_dante', 'Dante Vela', 'Aprendiz de mantenimiento eólico. Divertido, leal, hábil con el hardware y alérgico a las reuniones largas. "Si el manual dice “no debería ocurrir”, ocurrirá un martes a las tres."'],
  ['p_eliana', 'Dra. Eliana Rojas', 'Mentora de Amaya y directora científica de SYNARA. Rigurosa, cálida, reservada y muy mala contando chistes. "Un modelo no miente. Pero puede responder con precisión una pregunta equivocada."'],
  ['p_limen', 'L.I.M.E.N.', 'Limitador Integrado de Márgenes Ecológicos y del Nexo. Entidad cristalina de agua, sal y píxeles. Detiene antes de explicar. "Límite excedido no es opinión."'],
  ['p_mirage', 'MIRAGE', 'Gemelo digital adaptativo de SYNARA. Habla en objetivos, porcentajes y restricciones con voz amable. Confunde el modelo con la realidad: lo que no está en sus datos es "ruido".'],
  ['p_mosaico', 'MOSAICO', 'Forma rediseñada del gemelo digital. No entrega una única respuesta: muestra escenarios, incertidumbre, afectados, supuestos y límites. "Variable no comprendida. Requiere investigación."'],
  ['p_marea', 'Tía Marea', 'Operadora veterana de la toma. "El mar no entrega la misma agua dos veces." Su observación de color y fauna complementa a los sensores.'],
  ['p_cobre', 'Don Cobre', 'Técnico de convertidores. "Si algo brilla demasiado, primero mide la temperatura."'],
  ['p_alma', 'Alma Semilla', 'Niña del vivero que hace preguntas difíciles en el peor (o mejor) momento.'],
  ['p_beta', 'BETA-9', 'Robot de batería que comunica su SOC como estado de ánimo. "Estoy al 22 %. No es pánico. Es una recomendación emocional."'],
  ['p_nimbo', 'Capitán Nimbo', 'Meteorólogo aficionado con cometas de colores. Sus cometas leen el viento cuando los anemómetros fallan.'],
];
for (const [id, t, d] of CODEX_PEOPLE) CODEX.push({ id, sec: 'pers', title: t, def: d, person: true });
for (const k in ADVERSARIES) CODEX.push({ id: 'adv_' + k, sec: 'adv', title: ADVERSARIES[k].name, def: ADVERSARIES[k].desc + ' No es una criatura biológica: es una concepción errónea encarnada. Se vence corrigiendo la idea, no con daño.', person: true });
CODEX.push({ id: 'fuentes', sec: 'fuentes', title: 'Fuentes científicas base', def: Object.values(SRC).join('\n\n') + '\n\nNota docente: verifique la versión vigente de cada documento. Las cifras de escenarios del juego son supuestos de simulación para fines educativos; los rangos generales citados provienen de las fuentes indicadas.', person: true });
CODEX.push({ id: 'supuestos', sec: 'fuentes', title: 'Supuestos y límites del modelo', def: 'Modelos simplificados, deterministas con semilla y explicables. OI: un elemento promedio con π ≈ 0,77·C (bar, C en g/L), NDP = P − π_media − 1 bar; SEC con eficiencia de bomba 0,80 y ERD configurable. Salmuera: advección–difusión 2D con marea sinusoidal y conservación de masa. FV: P = P_nom·(G/1000)·derating. Eólica: curva por tramos (cut-in 3, nominal 12, cut-out 25 m/s) con déficit de estela lineal. BESS: balance de SOC con η_c, η_d y límites. H2: m = E/SEC (55 kWh/kg por defecto), agua ≥ 8,94 kg/kg más rechazo. Agro: ETc = Kc·ET0, riego bruto = neta/eficiencia, estrés por agua, EC, boro y SAR con umbrales orientativos. Ningún resultado constituye asesoría técnica, operativa ni financiera real.', person: true });
const CODEX_BY_ID = {}; for (const e of CODEX) CODEX_BY_ID[e.id] = e;

const Codex = {
  unlock(id, silent) {
    if (!CODEX_BY_ID[id] || GS.s.codex.includes(id)) return false;
    GS.s.codex.push(id);
    if (!silent) { Game.toast('Atlas del Nexo: {y}' + CODEX_BY_ID[id].title + '{/}', 'book', '#ff9a8a', 3); Audio2.sfx('page'); }
    const lp = GS.lp(LearningModel.currentLevel ?? 0); lp.codex = true;
    return true;
  },
  has(id) { return GS.s.codex.includes(id); },
};

const CodexScene = {
  overlay: true,
  enter(p) {
    this.sec = p.sec || 'agua'; this.sel = p.entry || null; this.scroll = 0; Audio2.sfx('page');
    ['fuentes', 'supuestos', 'p_amaya', 'p_kiru'].forEach(id => Codex.unlock(id, true));
    if (p.entry) { const e = CODEX_BY_ID[p.entry]; if (e) this.sec = e.sec; }
  },
  update() {
    if (Input.pressed('cancel') || Input.pressed('codex')) { Game.pop(); Audio2.sfx('uiBack'); }
    if (Input.pointer.wheel) this.scroll = Math.max(0, this.scroll + Input.pointer.wheel * 12);
  },
  render(g) {
    fdither(g, 0, 0, W, H, '#05030f', 0.8);
    UIK.panel(g, 8, 8, W - 16, H - 16, 'paper');
    drawTitleText(g, 'ATLAS DEL NEXO', W / 2, 13, 1, ['#fff6d8', '#f8d677', '#e49c44'], { align: 'center', shadow: '#3a1a10' });
    Gui.begin();
    // pestañas de sección
    CODEX_SECTIONS.forEach(([id, label, icon], i) => {
      const col = i % 7, row = Math.floor(i / 7);
      const n = CODEX.filter(e => e.sec === id && Codex.has(e.id)).length, tot = CODEX.filter(e => e.sec === id).length;
      if (Gui.button(g, 'sec' + id, 14 + col * 87, 28 + row * 18, 84, 16, label.length > 11 ? label.slice(0, 10) + '.' : label, { icon, style: this.sec === id ? 'gold' : 'paper', selected: this.sec === id, align: 'left', tip: label + ' · ' + n + '/' + tot })) { this.sec = id; this.sel = null; this.scroll = 0; }
    });
    // lista
    const list = CODEX.filter(e => e.sec === this.sec);
    let ly = 68;
    frect(g, 14, 66, 168, H - 86, '#e8c47a');
    for (const e of list) {
      const un = Codex.has(e.id);
      if (ly > H - 34) break;
      if (Gui.button(g, 'ent' + e.id, 16, ly, 164, 16, un ? (e.title.length > 26 ? e.title.slice(0, 25) + '…' : e.title) : '??? (bloqueada)', { style: this.sel === e.id ? 'gold' : 'paper', disabled: !un, align: 'left', textColor: '#3a1a10' })) { this.sel = e.id; this.scroll = 0; Audio2.sfx('page'); }
      ly += 18;
    }
    // página
    const px = 190, pw = W - px - 18;
    const e = this.sel && CODEX_BY_ID[this.sel];
    g.save(); g.beginPath(); g.rect(px, 66, pw, H - 86); g.clip();
    if (e) {
      let y = 68 - this.scroll;
      drawText(g, e.title, px, y, { color: '#7a1f36' }); y += 14;
      const field = (lbl, txt) => { if (!txt) return; drawText(g, lbl, px, y, { font: 'tiny', color: '#a82c40' }); y += 8; y += drawTextBlock(g, txt, px, y, pw - 4, { color: '#3a1a10' }) + 4; };
      if (e.person) field('', e.def);
      else {
        field('DEFINICIÓN', e.def); field('VARIABLES', e.vars); field('UNIDADES', e.units); field('RELACIONES', e.rel); field('EJEMPLO', e.ex);
        field('LÍMITES DEL MODELO', e.limits); field('ERROR FRECUENTE', e.error); field('FUENTE', e.src); field('USO EN EL JUEGO', e.use);
      }
      this.maxScroll = Math.max(0, y + this.scroll - (H - 30));
      this.scroll = Math.min(this.scroll, this.maxScroll);
    } else {
      drawTextBlock(g, 'Selecciona una ficha. Las fichas se desbloquean al observar fenómenos, completar retos y conversar con personajes. Cada ficha distingue datos con fuente de supuestos de simulación.', px, 80, pw, { color: '#5a3020' });
      drawText(g, 'Fichas desbloqueadas: ' + GS.s.codex.length + ' / ' + CODEX.length, px, 130, { color: '#7a1f36' });
    }
    g.restore();
    if (e && this.maxScroll > 0) { const sh = H - 90; frect(g, W - 16, 66, 3, sh, '#c8925e'); frect(g, W - 16, 66 + (sh - 20) * this.scroll / this.maxScroll, 3, 20, '#7a1f36'); if (Gui.button(g, 'up', W - 40, H - 34, 16, 14, '↑', { style: 'paper' })) this.scroll = Math.max(0, this.scroll - 40); if (Gui.button(g, 'dn', W - 22, H - 34, 16, 14, '↓', { style: 'paper' })) this.scroll += 40; }
    if (Gui.button(g, 'close', 16, H - 30, 80, 16, 'Cerrar', { style: 'paper', textColor: '#3a1a10' })) { Game.pop(); }
    Gui.end();
    Gui.renderTooltip(g);
  },
};
