/* =====================================================================
   24_codex_more.js — Fichas adicionales del Atlas del Nexo (sección Nexo
   y conceptos transversales usados por varios capítulos).
   ===================================================================== */
CODEX_SECTIONS.unshift(['nexo', 'Nexo', 'mosaic']);
function addCodex(e) { if (CODEX_BY_ID[e.id]) return; CODEX.push(e); CODEX_BY_ID[e.id] = e; }

addCodex({ id: 'nexo', sec: 'nexo', title: 'Nexo agua–energía–alimentos–ecosistemas', def: 'Enfoque que estudia juntos los sistemas de agua, energía y alimentos porque comparten recursos y se afectan entre sí: producir agua consume energía, producir energía puede consumir agua, y regar alimentos depende de ambos. Los ecosistemas reciben descargas y aportan servicios.', vars: 'Demanda de agua, demanda de energía, reservas, generación renovable, producción de alimentos e hidrógeno.', units: 'Agua en m³ o m³/h; potencia en kW; energía en kWh; hidrógeno en kg o kg/h.', rel: 'Optimizar un subsistema aislado puede empeorar otro: más H2 → más agua y electricidad desviadas; más riego → menos reserva.', ex: 'En SYNARA, 1 m³ de permeado cuesta ≈ 3 kWh y 1 kg de H2 ≈ 55 kWh y ≈ 9 kg de agua (' + SIM_NOTE + ')', limits: 'El juego usa balances agregados por hora; no modela redes de distribución completas.', error: 'Creer que una sola tecnología resuelve todo el problema.', src: SRC.faoDesal + ' ' + SRC.irenaWater, use: 'Nivel 00: reconstruyes el diagrama vivo de SYNARA.' });
addCodex({ id: 'limites_sistema', sec: 'nexo', title: 'Límites del sistema', def: 'Frontera que define qué está dentro del análisis y qué queda fuera. Todo lo que cruza la frontera es una entrada o una salida (agua de mar, sol, viento, salmuera, calor, productos).', vars: 'Entradas, salidas, frontera, supuestos.', units: 'Las mismas de cada flujo; se suman solo flujos del mismo tipo y unidad.', rel: 'Cambiar la frontera cambia la conclusión: el H2 parece "limpio" si la frontera excluye la red que lo alimenta.', ex: 'Si la frontera de SYNARA excluye el mar, la salmuera "desaparece" del análisis; si lo incluye, aparece su impacto.', limits: 'Toda frontera es una decisión; debe declararse.', error: 'Ocultar impactos dejándolos fuera de la frontera.', src: SRC.unesco, use: 'Nivel 00: la Lente Nexo dibuja la frontera del sistema.' });
addCodex({ id: 'flujos_reservas', sec: 'nexo', title: 'Flujos y reservas (stocks)', def: 'Una reserva (tanque, batería, almacén de H2) cambia según la diferencia entre lo que entra y lo que sale. Si las salidas superan a las entradas, la reserva baja aunque "se esté produciendo".', vars: 'Reserva S, entradas Qin, salidas Qout, tiempo Δt.', units: 'S en m³ (agua), kWh (energía), kg (H2); flujos en m³/h, kW, kg/h.', rel: 'ΔS = (Qin − Qout) · Δt.', ex: 'Si la OI produce 42 m³/h pero se extraen 50 m³/h, el tanque baja 8 m³ cada hora.', limits: 'Se ignoran pérdidas por fugas y evaporación salvo cuando se indican.', error: 'Pensar que producir significa acumular.', src: 'Balance de masa (principio de conservación).', use: 'Nivel 00: el tanque no crece aunque la planta produce.' });
addCodex({ id: 'unidades', sec: 'nexo', title: 'Unidades: no mezclar peras con kilovatios', def: 'Cada flujo tiene su unidad: agua en m³/h o L/s, potencia eléctrica en kW, energía en kWh, hidrógeno en kg/h. Solo se suman cantidades con la misma unidad física.', vars: 'Caudal, potencia, energía, masa.', units: '1 m³ = 1000 L; 1 kWh = 1 kW durante 1 h; 1 kg H2 ≈ 33,3 kWh (PCI).', rel: 'Convertir antes de comparar; revisar órdenes de magnitud.', ex: '300 vasos de 250 mL = 75 L = 0,075 m³.', limits: 'El juego redondea a dos o tres cifras significativas.', error: 'Confundir kW (ritmo) con kWh (cantidad) o L con m³.', src: 'Sistema Internacional de Unidades (BIPM).', use: 'Nivel 00: misión "Limonada para trescientos".' });
addCodex({ id: 'variabilidad', sec: 'nexo', title: 'Variabilidad renovable', def: 'La generación solar depende de la hora, las nubes y el polvo; la eólica, de la velocidad del viento (que cambia en minutos). Ninguna está disponible de forma constante sin almacenamiento o cargas flexibles.', vars: 'Irradiancia, velocidad de viento, potencia generada.', units: 'W/m², m/s, kW.', rel: 'La potencia eólica crece con el cubo del viento dentro de la curva de la turbina; la solar cae a cero de noche.', ex: 'Un molino de papel en un techo gira más rápido que en la calle: el viento cambia con la altura y los obstáculos.', limits: 'El juego usa series sintéticas con semilla.', error: 'Asumir que toda energía renovable está disponible siempre.', src: SRC.irenaStrat, use: 'Nivel 00: misión "Molinos de papel".' });
addCodex({ id: 'conclusion', sec: 'steam', title: 'Conclusión sustentada', def: 'Una conclusión es sustentada cuando los datos disponibles la apoyan y se han considerado explicaciones alternativas. Una acción que parece sabotaje puede tener otra causa.', vars: 'Evidencia, hipótesis, explicaciones alternativas.', units: '—', rel: 'Más evidencia independiente → más confianza; una sola observación → hipótesis, no conclusión.', ex: 'LIMEN cerró una válvula: ¿sabotaje o protección? Hace falta saber qué medía.', limits: 'En el juego algunas pistas solo se interpretan después.', error: 'Confundir la primera interpretación con la verdad.', src: SRC.unesco, use: 'Tablero de evidencias (TAB).' });
